.ONESHELL:

.DEFAULT_GOAL :=run venv

# Variables
PROJECT_NAME = SusprojectFinal
PYTHON_FILES = *.py
OUTPUT_FORMAT = png

#Setup
setup: requirements.txt	
	pip install -r requirements.txt	

# Targets
uml:
	pyreverse -o png -p SusprojectFinal SusprojectFinal/*.py

#Clean 
# Setup a venv and install packages.
#
venv:
	[ -d .venv ] || $(PYTHON) -m venv .venv
	@printf "Now activate the Python virtual environment.\n"
	@printf "On Unix and Mac, do:\n"
	@printf ". .venv/bin/activate\n"
	@printf "On Windows (bash terminal), do:\n"
	@printf ". .venv/Scripts/activate\n"
	@printf "Type 'deactivate' to deactivate.\n"

pyreverse:
	@$(call MESSAGE,$@)
	install -d doc/pyreverse
	pyreverse /*.py
	dot -Tpng classes.dot -o doc/pyreverse/classes.png
	dot -Tpng packages.dot -o doc/pyreverse/packages.png
	rm -f classes.dot packages.dot

doc: pdoc pyreverse #pydoc sphinx
